### ISSUE TITLE
Prepare for Symfony 6

### ISSUE THREAD

**Issue by daften** [bresam/ivory-google-map#15]
This pops up since Symfony 5.3:

```
Since symfony/event-dispatcher 5.3: Configuring 

"Symfony\Component\EventDispatcher\DependencyInjection\RegisterListenersPass" is deprecated.
```

The class is created in \Ivory\GoogleMapBundle\DependencyInjection\Compiler\RegisterHelperListenerPass::__construct.

This also happened in other bundles, e.g. https://github.com/KnpLabs/KnpPaginatorBundle/issues/704 and this is where the custom tags were deprecated: https://github.com/KnpLabs/KnpPaginatorBundle/commit/44ab47fe786656203cbda3e2b83fdbe29445dc30

**Comment by bresam** [comment]
Should be fixed in latest 6.0.0
Thank you for reporting
