### ISSUE TITLE
Missing class "LegacyEventDispatcherProxy" after 3.0.8 upgrade

### ISSUE THREAD

**Issue by davidromani** [bresam/ivory-google-map#16]
Hello!

After a composer update ivory/google-map has been updated from 3.0.4 to 3.0.8 version and I started to get this error:

```
[Symfony\Component\Debug\Exception\ClassNotFoundException]
Attempted to load class "LegacyEventDispatcherProxy" from namespace "Symfony\Component\EventDispatcher".
Did you forget a "use" statement for another namespace?
```

I suspect that there is a problem with `Ivory\GoogleMap\Helper\Subscriber\AbstractDelegateSubscriber` because it's importing a missing class. Maybe there is a problem with `symfony/event-dispatcher` required version? I've 2.8.52 version.

Any hint? Thanks in advance.

**Comment by bresam** [comment]
I think you are right. Probably there is an issue with the required event-dispatcher version.
Have you already found out more about this?

**Comment by davidromani** [comment]
not for now, sorry

**Comment by bresam** [comment]
can't reproduce on latest v 6.0.0, seems to be fixed
