### ISSUE TITLE
Cannot use if FOSRestBundle is version 3.0 or greater

### ISSUE THREAD

**Issue by dario-innatial** [bresam/ivory-google-map#18]
FOS\RestBundle\Serializer\Normalizer\AbstractExceptionNormalizer does not exist in FOSRestBundle 3.0 and so it fails. I had to roll back to FOSRestBundle ^2.7

**Comment by bresam** [comment]
We don't use FOS\RestBundle\Serializer\Normalizer\AbstractExceptionNormalizer

Any more informations about that?

**Comment by dario-innatial** [comment]
Back then it was the error that we got. I could see the dependency being referenced in one of the library files. We were on symfony4.4. 
On new projects we are not using this library so I'm closing the issue as it does not affect us anymore. Thanks for your work anyway.
