### ISSUE TITLE
PHP 8.2 deprecations

### ISSUE THREAD

**Issue by InfinityMuenster** [bresam/ivory-google-map#21]
Hi,

found a PHP 8.2 deprecation:

Deprecated error: uniqid(): Passing null to parameter #1 ($prefix) of type string is deprecated in file \vendor\ivory\google-map\src\Utility\VariableAwareTrait.php (Line: 31)

Line has to be changed to:

$this->variable = $prefix.substr_replace(uniqid('', true), '', 14, 1);

Thanks a lot for keeping this package alive ;-)

**Comment by bresam** [comment]
solved in v6 branch and hopefully released soon
