### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by Chris53897** [bresam/ivory-google-map#25]
i am working on this

**Comment by Chris53897** [comment]
@bresam At which PHP Versions are your real word projects? Mine are on PHP 8.3

**Comment by bresam** [comment]
on 8.2
Some hoster are a bit slower with getting 8.3 installed ^^
Would you like to change supported php version?
8.1 is basically still supported by end of the year but i am open to support only php ^8.2
Up to you

**Comment by Chris53897** [comment]
i am thinking about it.
As there are not many user of this repo (contributers), the maintainence cost should be low.
I first want to see the result of the improved ci with forced symfony versions

**Comment by bresam** [comment]
@Chris53897 I've created a new tag 6.0.3 on google-map to get the latest changes on requiring google-map-bundle:v6.x-de

**Comment by Chris53897** [comment]
Perfect, thanks

**Comment by bresam** [comment]
@Chris53897 and i have tested it on our sf6.4 Project, works like a charm ;-)

**Comment by Chris53897** [comment]
Thats is great to hear. i will probably get the permission from my company for the google maps api key tomorrow.
After that i can start testing in a real project.
