### ISSUE TITLE
Unit tests: Fix errors and deprecations

### ISSUE THREAD

**Issue by bresam** [bresam/ivory-google-map#37]
Need to fix
 - errors
 - deprecations

**Comment by bresam** [comment]
@Chris53897
I have tested with --prefer-lowest dependencies and fixed the last unit test error related to outdated placeIDs used in tests.

**Comment by bresam** [comment]
@Chris53897 do you think we should try to enable functional tests too?

**Comment by Chris53897** [comment]
Of course you can enable them and check the ci for the actual result.
I did not get the permission from the company for the Google Maps API Key.
So i am afraid i can not invest too much time anymore here to help here. Sorry

**Comment by bresam** [comment]
No problem, thank you very much for the work you did on that project, i really appreciate this!
Have you had the opportunity to test it on a real world sf7 project yet?

**Comment by Chris53897** [comment]
I got it installed and running without errors (that was a big step until the last try)
The Form-Field is displayed, but not working for missing key. This is expected.
If i find some free time, i will create a personal Google Maps API Key to test it.
But for now i need to keep up on some other tasks.
