### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by Chris53897** [bresam/ivory-google-map#38]
it would be great if this repo follows the default github branching system.
This will help other contributors.

Options: 
a) make `v6` the default branch
b) rename `master` to 5.x? (depends on actual use-case).  rename `v6` branch to `main`. Make `main` the new default branch. (my favourite)
c) rename `master` to 5.x? (depends on actual use-case).  rename `v6` branch to `master`. Make `master` the new default branch.

Of course there are more options with branch-aliases.

After that a new release would be great. Just as a indicator that this repo is alive and kicking ;)
Last actual visible releae is October 2021.
Same for the symfony-bundle.

**Comment by bresam** [comment]
@Chris53897 just created new releases and merged v6 into master.
older versions are still available anyways by the older tags.

Thank you again for your collaboration.

**Comment by Chris53897** [comment]
great. Thanks
